mod reverse_string;
pub use reverse_string::reverse_string;
mod word_count;
pub use word_count::word_count;
mod clamp_int;
pub use clamp_int::clamp_int;
mod normalize_whitespace;
pub use normalize_whitespace::normalize_whitespace;
mod common_prefix;
pub use common_prefix::common_prefix;
mod remove_suffix;
pub use remove_suffix::remove_suffix;
mod frequencies_ints;
pub use frequencies_ints::frequencies_ints;
mod range_ints;
pub use range_ints::range_ints;
mod flatten_ints;
pub use flatten_ints::flatten_ints;
